PATHS:
  ROOT_PATH: '/storage/shafner/continuous_urban_change_detection'
  SPACENET7_PATH: '/storage/shafner/spacenet7'  # this is the original SpaceNet7 dataset
  OSCD_PATH: '/storage/shafner/urban_change_detection/OSCD_dataset'  # this is the original OSCD dataset

DATASET_NAMES:
  SPACENET7: 'spacenet7_s1s2_dataset_v3'
  OSCD: 'oscd_s1s2_dataset'

INPUT:
  TYPE: 'cnn' # cnn or satellite
  SENSOR: 'sentinel1' # sentinel1 or sentinel2
  BAND: 'VV' # see available bands
  CONFIG_NAME_DICT:
    sar: 'sar_jaccardmorelikeloss'
    optical: 'optical_jaccardmorelikeloss'
    fusion: 'fusionda_cons05_jaccardmorelikeloss'

INCLUDE_MASKED_DATA: True

PLOTTING:
  FONTSIZE: 16
  PLOTSIZE: 3

SUBSET_SPACENET7:
  ACTIVATE: False
  AOI_IDS: [
    'L15-0457E-1135N_1831_3648_13',
    'L15-0566E-1185N_2265_3451_13',
    'L15-0977E-1187N_3911_3441_13',
    'L15-1203E-1203N_4815_3378_13',
    'L15-1204E-1202N_4816_3380_13',
    'L15-1276E-1107N_5105_3761_13',
    'L15-1296E-1198N_5184_3399_13',
    'L15-1848E-0793N_7394_5018_13',
  ]

SUBSET_OSCD:
  ACTIVATE: False
  AOI_IDS: []