SEED: 7
DEBUG: True
LOG_FREQ: 1000
OUTPUT_BASE_DIR: '/storage/shafner/continuous_urban_change_detection/networks'
CHECKPOINTS:
  SAVE: [10]

MODEL:
  TYPE: 'gru'
  OUT_CHANNELS: 2
  IN_CHANNELS: 1
  LOSS_TYPE: 'L2'
  TOPOLOGY: [64, 128,]

DATALOADER:
  NUM_WORKER: 16
  SHUFFLE: True
  CONFIG_NAME: 'optical_jaccardmorelikeloss'
  INPUT: 'prob'  # prob or features
  OUTPUT: 'change'  # change or change_date

DATASETS:
  ROOT_PATH: '/storage/shafner/continuous_urban_change_detection'
  NAME: 'timeseries_dataset'
  AOI_IDS:
    TRAINING: ['L15-0358E-1220N_1433_3310_13']
    VALIDATION: []

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 128
  EPOCHS: 20
  OPTIMIZER: 'adamw'

AUGMENTATION:
  NOISE: False
