SEED: 7
DEBUG: True
LOG_FREQ: 100
OUTPUT_BASE_DIR: '/storage/shafner/continuous_urban_change_detection/networks'
SAVE_CHECKPOINTS: [20]
INFERENCE:
  CHECKPOINT: 0

MODEL:
  TYPE: 'gru'
  OUT_CHANNELS: 1
  IN_CHANNELS: 12
  LOSS_TYPE: 'L2'
  TOPOLOGY: [64, 128,]

DATALOADER:
  NUM_WORKER: 16
  SHUFFLE: True
  CONFIG_NAME: 'buildings'
  LABEL_THRESH: 0.0


DATASETS:
  PATH: '/storage/shafner/continuous_urban_change_detection/spacenet7_s1s2_dataset/'
  TRAINING: []
  VALIDATION: []
  SUBSET_FEATURES: False
  SUBSET_PERCENTILE: 90

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 8
  EPOCHS: 20
  OPTIMIZER: 'adamw'

AUGMENTATION:
  NOISE: False
